package QLSV;

import DAO.AccountDAO;
import POJOS.Account;
import javax.swing.JOptionPane;
import static QLSV.DangNhap.account;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form GiaoVu
     */
    public DoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_luu = new javax.swing.JButton();
        txt_passwordnow = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_passwordnew = new javax.swing.JPasswordField();
        txt_passwordnewagain = new javax.swing.JPasswordField();
        bt_quayve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        bt_luu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bt_luu.setText("Lưu");
        bt_luu.setName("bt_luu"); // NOI18N
        bt_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luuActionPerformed(evt);
            }
        });

        txt_passwordnow.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_passwordnow.setName("txt_passwordnow"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("ĐỔI MÂT KHẨU");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu hiện tại");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu mới");

        txt_passwordnew.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_passwordnew.setName("txt_password"); // NOI18N

        txt_passwordnewagain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_passwordnewagain.setName("txt_password"); // NOI18N

        bt_quayve.setText("Quay Về");
        bt_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quayveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_passwordnew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_passwordnow, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_passwordnewagain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(bt_quayve)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_passwordnow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_passwordnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_passwordnewagain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_luu)
                    .addComponent(bt_quayve))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luuActionPerformed
        // TODO add your handling code here:
        String passnow=new String(txt_passwordnow.getPassword());
        String passnew=new String(txt_passwordnew.getPassword());
        String passnewagain=new String(txt_passwordnewagain.getPassword());

        if (account!=null && account.getPassword().equals(passnow)) 
        {
            if(passnew.equals(passnewagain))
            {
                Account accountUpdate = account;
                accountUpdate.setPassword(passnew);
                boolean updateAccount = AccountDAO.updateAccount(accountUpdate);
                if(AccountDAO.updateAccount(account)==true)
                {
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công.");
                    GiaoVu gv = new GiaoVu();
                    gv.setVisible(true);
                    this.setVisible(false);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Mật khẩu mới và nhập lại mật khẩu mới không trùng khớp.");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại chưa đúng.");
        }

    }//GEN-LAST:event_bt_luuActionPerformed

    private void bt_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quayveActionPerformed
        // TODO add your handling code here:
        if(account.getUser().equals("giaovu"))
        {
            GiaoVu gv = new GiaoVu();
            gv.setVisible(true);
            this.setVisible(false);
        }
        else{
            SinhVien sv = new SinhVien();
            sv.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bt_quayveActionPerformed
    
    private boolean kiemtra(String passnow, String passnew, String passnewagain) {
        boolean kiemtra = false;
        StringBuilder msgErr = new StringBuilder();

        if (passnow.equals("")) {
            kiemtra = true;
            msgErr.append("Vui lòng nhập mật khẩu hiện tại.\n");
        }

        if (passnew.equals("")) {
            kiemtra = true;
            msgErr.append("Vui lòng nhập mật khẩu mới.\n");
        }
        if (passnewagain.equals("")) {
            kiemtra = true;
            msgErr.append("Vui lòng nhập mật khẩu mới lần nửa.");
        }
        if(kiemtra==true)
        {
            JOptionPane.showMessageDialog(this, msgErr);
        }
        
        return kiemtra;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_luu;
    private javax.swing.JButton bt_quayve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPasswordField txt_passwordnew;
    private javax.swing.JPasswordField txt_passwordnewagain;
    private javax.swing.JPasswordField txt_passwordnow;
    // End of variables declaration//GEN-END:variables
}
