package QLSV;

import POJOS.Account;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class GiaoVu extends javax.swing.JFrame {

    /**
     * Creates new form GiaoVu
     */
    public GiaoVu() {
        initComponents();
    }

//    GiaoVu(DangNhap aThis) {
//        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        bt_doimatkhau = new javax.swing.JButton();
        bt_taopkdiem = new javax.swing.JButton();
        bt_xemdspk = new javax.swing.JButton();
        bt_qllop = new javax.swing.JButton();
        bt_qltkb = new javax.swing.JButton();
        bt_qldiem = new javax.swing.JButton();
        bt_dangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_doimatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_doimatkhau.setText("Đổi Mật Khẩu");
        bt_doimatkhau.setName("bt_doimk"); // NOI18N
        bt_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_doimatkhauActionPerformed(evt);
            }
        });

        bt_taopkdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_taopkdiem.setText("Tạo Phúc Khảo Điểm");
        bt_taopkdiem.setName("bt_taopkdiem"); // NOI18N
        bt_taopkdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_taopkdiemActionPerformed(evt);
            }
        });

        bt_xemdspk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_xemdspk.setText("Xem DS Phúc Khảo");
        bt_xemdspk.setName("bt_xemdspk"); // NOI18N
        bt_xemdspk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemdspkActionPerformed(evt);
            }
        });

        bt_qllop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_qllop.setText("Quản Lý Lớp");
        bt_qllop.setName("bt_qllop"); // NOI18N
        bt_qllop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_qllopActionPerformed(evt);
            }
        });

        bt_qltkb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_qltkb.setText("Quản Lý TKB");
        bt_qltkb.setName("bt_qltkb"); // NOI18N
        bt_qltkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_qltkbActionPerformed(evt);
            }
        });

        bt_qldiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_qldiem.setText("Quản Lý Điểm");
        bt_qldiem.setName("bt_qldiem"); // NOI18N
        bt_qldiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_qldiemActionPerformed(evt);
            }
        });

        bt_dangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_dangxuat.setText("Đăng Xuất");
        bt_dangxuat.setName("bt_doimk"); // NOI18N
        bt_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_doimatkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_taopkdiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(bt_xemdspk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_qldiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_qllop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(bt_qltkb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_qllop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_qltkb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_qldiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(bt_taopkdiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_xemdspk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_doimatkhau)
                .addGap(18, 18, 18)
                .addComponent(bt_dangxuat)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_doimatkhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau doimk = new DoiMatKhau();
        doimk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_doimatkhauActionPerformed

    private void bt_qllopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_qllopActionPerformed
        // TODO add your handling code here:
        QuanLyLop qllop = new QuanLyLop();
        qllop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_qllopActionPerformed

    private void bt_qltkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_qltkbActionPerformed
        // TODO add your handling code here:
        QuanLyTKB qltkb = new QuanLyTKB();
        qltkb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_qltkbActionPerformed

    private void bt_qldiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_qldiemActionPerformed
        // TODO add your handling code here:
        QuanLyDiem qldiem = new QuanLyDiem();
        qldiem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_qldiemActionPerformed

    private void bt_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dangxuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_dangxuatActionPerformed

    private void bt_taopkdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_taopkdiemActionPerformed
        // TODO add your handling code here:
        TaoPhucKhaoDiem dn = new TaoPhucKhaoDiem();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_taopkdiemActionPerformed

    private void bt_xemdspkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemdspkActionPerformed
        // TODO add your handling code here:
        XemDSXinPhucKhao dn = new XemDSXinPhucKhao();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_xemdspkActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dangxuat;
    private javax.swing.JButton bt_doimatkhau;
    private javax.swing.JButton bt_qldiem;
    private javax.swing.JButton bt_qllop;
    private javax.swing.JButton bt_qltkb;
    private javax.swing.JButton bt_taopkdiem;
    private javax.swing.JButton bt_xemdspk;
    private javax.swing.JPanel jPanel14;
    // End of variables declaration//GEN-END:variables
}
