package QLSV;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import DAO.DiemLopMonDAO;
import DAO.LopDAO;
import DAO.MonDAO;
import POJOS.Diemlopmon;
import POJOS.DiemlopmonId;
import POJOS.Lop;
import POJOS.Mon;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class QuanLyDiem extends javax.swing.JFrame {

    private String[] columnNames = {
        "STT", "MSSV", "Họ Tên", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng", ""
    };
    /**
     * Creates new form QuanLyDiem
     */
    public QuanLyDiem() {
        initComponents();
        initLayoutlop();
        initLayoutmon();
    }

    private void initLayoutlop() {
        List<Lop> DSLop = LopDAO.getlistlop();
        if(DSLop.size()>0)
        {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            //System.out.println("có");
            for (Lop l : DSLop) {
                Lop _l = LopDAO.getlop(l.getMalop());
                comboboxModel.addElement(l.getMalop());
            }
            jcb_lop.setModel(comboboxModel);
        } else 
        {
            jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }
    
    private void initLayoutmon() {
        List<Mon> DSmon = MonDAO.getlistmon();
        if(DSmon.size()>0)
        {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            //System.out.println("có");
            for (Mon m : DSmon) {
                //Mon _m = MonDAO.getmon(m.getMamon());
                comboboxModel.addElement(m.getMamon());
            }
            jcb_mon.setModel(comboboxModel);
        } else 
        {
            jcb_mon.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_import = new javax.swing.JButton();
        bt_xemdiem = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcb_lop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jcb_mon = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_quayve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_dau = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tldau = new javax.swing.JTextField();
        txt_tlrot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_rot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_import.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_import.setText("Import Bảng Điểm");
        bt_import.setName("bt_importdiem"); // NOI18N
        bt_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_importActionPerformed(evt);
            }
        });

        bt_xemdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_xemdiem.setText("Xem Điểm");
        bt_xemdiem.setName("bt_xemdiem"); // NOI18N
        bt_xemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemdiemActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("Sửa Điểm");
        jButton22.setName("bt_suadiem"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lớp:");

        jcb_lop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_lopActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Môn:");

        jcb_mon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_mon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_monActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        bt_quayve.setText("Quay Về");
        bt_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quayveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Số sinh viên đậu:");

        txt_dau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_dau.setText("0");
        txt_dau.setDoubleBuffered(true);
        txt_dau.setEnabled(false);
        txt_dau.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Tỉ lệ:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Tỉ lệ:");

        txt_tldau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_tldau.setText("0");
        txt_tldau.setEnabled(false);

        txt_tlrot.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_tlrot.setText("0");
        txt_tlrot.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Số sinh viên rớt:");

        txt_rot.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_rot.setText("0");
        txt_rot.setDoubleBuffered(true);
        txt_rot.setEnabled(false);
        txt_rot.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bt_import)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_dau)
                                    .addComponent(txt_rot))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 167, Short.MAX_VALUE)
                                .addComponent(bt_xemdiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_tlrot))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_tldau, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_quayve)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_import)
                    .addComponent(bt_quayve)
                    .addComponent(jLabel3)
                    .addComponent(txt_dau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tldau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tlrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_rot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_xemdiem)
                    .addComponent(jButton22)
                    .addComponent(jLabel6)
                    .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcb_mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quayveActionPerformed
        // TODO add your handling code here:
        GiaoVu gv = new GiaoVu();
        gv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_quayveActionPerformed

    private void bt_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_importActionPerformed
        // TODO add your handling code here:
        ChosseFile("Choose file import");
    }//GEN-LAST:event_bt_importActionPerformed

    private void jcb_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_lopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_lopActionPerformed

    private void jcb_monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_monActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcb_monActionPerformed

    private void bt_xemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemdiemActionPerformed
        // TODO add your handling code here:
        String malop =(String) jcb_lop.getSelectedItem();
        String mamon =(String) jcb_mon.getSelectedItem();
        if (!malop.equals("null")&&!mamon.equals("null")) {
            xemdsdiem(malop, mamon);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn mã lớp, mã môn.", "Notification", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_xemdiemActionPerformed

    private void xemdsdiem(String malop, String mamon)
    {
        int stt = 1,d=0,r=0;
        float tld=0,tlr=0;
        List<Object[]> dsdlm = DiemLopMonDAO.getlistdiemlopmon(malop,mamon);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        if(dsdlm.size()>0)
        {
            for (Object[] dlm : dsdlm){
                String[] rows = new String[8];
                rows[0] = String.valueOf(stt);
                rows[1] = dlm[0].toString();
                rows[2] = dlm[1].toString();
                rows[3] = dlm[2].toString();
                rows[4] = dlm[3].toString();
                rows[5] = dlm[4].toString();
                rows[6] = dlm[5].toString();
                if(Float.parseFloat(dlm[5].toString())>=5)
                {
                    rows[7] = "Đậu";
                    d++;
                }
                else
                {
                    rows[7] = "Rớt";
                    r++;
                }
                tableModel.addRow(rows);
                stt++;
            }
            jTable1.setModel(tableModel);
            txt_dau.setText(String.valueOf(d));
            txt_rot.setText(String.valueOf(r));
            tld=(d * 100) / dsdlm.size();
            tlr=100-tld;
//            tlr=(d * (float)100) / dsdlm.size();
//            tld=(float) Math.round(tlr * 10) / 10;
//            tlr=100-tld;
            txt_tldau.setText(String.valueOf(tld)+"%");
            txt_tlrot.setText(String.valueOf(tlr)+"%");
        }
        else
        {
            jTable1.setModel(tableModel);
        }
    }
    
    private void ChosseFile(String choose_file_import) {
        JFileChooser fileChooser = new JFileChooser();
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            insertdata(selectedFile);
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }
    
    private void insertdata(File selectedFile) {
        String csvFile = selectedFile.toString();
        String cvsSplitBy = ",";
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(csvFile));
            String line = "";
            int d=0;
            String mssvnoinsert="";
            String malop = null;
            String mamon = null;
            try {
                if((line = br.readLine()) != null)
                {
                    String [] dlm = line.split(cvsSplitBy);
                    malop=dlm[0];
                    mamon=dlm[1];
                }
                while ((line = br.readLine()) != null) {                   
                    String [] dlm = line.split(cvsSplitBy);
                    DiemlopmonId dlmid = new DiemlopmonId(dlm[6], dlm[7], dlm[0]);
                    Diemlopmon insertdlm = new Diemlopmon(dlmid, Float.parseFloat(dlm[2]), Float.parseFloat(dlm[3]), Float.parseFloat(dlm[4]), Float.parseFloat(dlm[5]));
                    if(DiemLopMonDAO.update(insertdlm)==true)
                    {
                        d++;       
                    }   
                    else
                    {
                        mssvnoinsert=dlm[0]+",";
                    }
                }
                JOptionPane.showMessageDialog(this, "Đã insert "+d+" Sinh viên.\nMã sinh viên:"+mssvnoinsert+"không có trong danh sách Lop môn "+malop+"-"+mamon);
            } catch (IOException ex) {
                Logger.getLogger(QuanLyLop.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_import;
    private javax.swing.JButton bt_quayve;
    private javax.swing.JButton bt_xemdiem;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcb_lop;
    private javax.swing.JComboBox jcb_mon;
    private javax.swing.JTextField txt_dau;
    private javax.swing.JTextField txt_rot;
    private javax.swing.JTextField txt_tldau;
    private javax.swing.JTextField txt_tlrot;
    // End of variables declaration//GEN-END:variables
}
