package QLSV;

import DAO.LopDAO;
import DAO.SinhVienDAO;
import DAO.AccountDAO;
import POJOS.Lop;
import POJOS.SinhVien;
import POJOS.Account;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class QuanLyLop extends javax.swing.JFrame {

    static String malop="";
    private String[] columnNames = {
        "STT", "Mã sinh viên", "Họ Tên", "Giới Tính", "CMND"
    };
    /**
     * Creates new form QuanLyLop
     */
    public QuanLyLop() {
        initComponents();
        initLayoutlop();
        this.bt_xoasv.setVisible(false);
        this.lbl_malop.setVisible(false);
    }
    private void initLayoutlop() {
        List<Lop> DSLop = LopDAO.getlistlop();
        if(DSLop.size()>0)
        {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            //System.out.println("có");
            for (Lop l : DSLop) {
                Lop _l = LopDAO.getlop(l.getMalop());
                comboboxModel.addElement(l.getMalop());
            }
            jcb_lop.setModel(comboboxModel);
        } else 
        {
            jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_importdslop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_themsv = new javax.swing.JButton();
        bt_xoasv = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcb_lop = new javax.swing.JComboBox();
        lbl_malop = new javax.swing.JLabel();
        bt_quayve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_importdslop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_importdslop.setText("Import Danh Sách Lớp");
        bt_importdslop.setName("bt_importlop"); // NOI18N
        bt_importdslop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_importdslopActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bt_themsv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_themsv.setText("Thêm Sinh Viên");
        bt_themsv.setName("bt_themsv"); // NOI18N
        bt_themsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themsvActionPerformed(evt);
            }
        });

        bt_xoasv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_xoasv.setText("Xóa Sinh Viên");
        bt_xoasv.setName("bt_xoasv"); // NOI18N
        bt_xoasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoasvActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lớp:");

        jcb_lop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_lopActionPerformed(evt);
            }
        });

        lbl_malop.setText("-1");

        bt_quayve.setText("Quay Về");
        bt_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quayveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_lop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bt_importdslop, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_xoasv)
                                .addGap(18, 18, 18)
                                .addComponent(bt_themsv))
                            .addComponent(bt_quayve, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_malop)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_importdslop)
                    .addComponent(bt_quayve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_malop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_xoasv)
                        .addComponent(bt_themsv))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themsvActionPerformed
        // TODO add your handling code here:
        if(!malop.equals(""))
        {
            ThemSinhVien tsv = new ThemSinhVien();
            tsv.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn lớp cần thêm sinh viên.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_themsvActionPerformed

    private void bt_importdslopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_importdslopActionPerformed
        // TODO add your handling code here:
        ChosseFile("Choose file import");
    }//GEN-LAST:event_bt_importdslopActionPerformed

    private void jcb_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_lopActionPerformed
        // TODO add your handling code here:
        //String malop = String.valueOf(jcb_lop.getItemAt(jcb_lop.getSelectedIndex()));
        malop =(String) jcb_lop.getSelectedItem();
        if (!malop.equals("null")) {
            xemdslop(malop);
        } else {
            JOptionPane.showMessageDialog(null, "Chưa có danh sách lớp học.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jcb_lopActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        lbl_malop.setText(model.getValueAt(i,1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quayveActionPerformed
        // TODO add your handling code here:
        GiaoVu gv = new GiaoVu();
        gv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_quayveActionPerformed

    private void bt_xoasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoasvActionPerformed
        // TODO add your handling code here:
        String mssv=lbl_malop.getText();
        if(mssv.equals("-1")||mssv.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên cần xóa.");
        }
        else{
            if(SinhVienDAO.deletesvlop(mssv)==true)
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công.");
                lbl_malop.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại.");
            }
        }
    }//GEN-LAST:event_bt_xoasvActionPerformed

    private void xemdslop(String malop) {
        int stt = 1;
        List<SinhVien> dssv = SinhVienDAO.getlistsv(malop);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        for (SinhVien sv : dssv) {
            String[] rows = new String[5];
            rows[0] = String.valueOf(stt);
            rows[1] = sv.getMssv();
            rows[2] = sv.getHoten();
            rows[3] = sv.getGt();
            rows[4] = sv.getCmnd();
            tableModel.addRow(rows);
            stt++;
        }
        jTable1.setModel(tableModel);
    }
    
    private void ChosseFile(String choose_file_import) {
        JFileChooser fileChooser = new JFileChooser();
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            insertdata(selectedFile);
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }

    private void insertdata(File selectedFile) {
        String csvFile = selectedFile.toString();
        String cvsSplitBy = ",";
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(csvFile));
            String line = "";
            int d=0;
            String mssvnoinsert="";
            try {
                if((line = br.readLine()) != null)
                {
                    String[] l = line.split(cvsSplitBy);
                    Lop insertlop = new Lop(l[0], l[1]);
                    if(LopDAO.createlop(insertlop)==true)
                    {
                        while ((line = br.readLine()) != null) {                   
                            String [] sv = line.split(cvsSplitBy);
                            SinhVien insertsv = new SinhVien(sv[0], sv[1], sv[2], sv[3], sv[4]);
                            Account inserta =new Account(sv[0], sv[0]);
                            if(SinhVienDAO.createSinhVien(insertsv)==true&&AccountDAO.createaccount(inserta)==true)
                            {
                                //&&AccountDAO.createaccount(inserta)==true
                                d++;       
                            }   
                            else
                            {
                                mssvnoinsert=sv[0]+",";
                            }
                        }
                    }
                }
                JOptionPane.showMessageDialog(this, "Đã insert " + d+" Sinh viên.\nMã sinh viên chưa đưa vào:"+mssvnoinsert);
            } catch (IOException ex) {
                Logger.getLogger(QuanLyLop.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyLop.class.getName()).log(Level.SEVERE, null, ex);
        }
        initLayoutlop();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_importdslop;
    private javax.swing.JButton bt_quayve;
    private javax.swing.JButton bt_themsv;
    private javax.swing.JButton bt_xoasv;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcb_lop;
    private javax.swing.JLabel lbl_malop;
    // End of variables declaration//GEN-END:variables
}
