package QLSV;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class SinhVien extends javax.swing.JFrame {
    /**
     * Creates new form SinhVien
     */
    public SinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_xemdiem = new javax.swing.JButton();
        bt_doimatkhau = new javax.swing.JButton();
        bt_dangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_xemdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_xemdiem.setText("Xem Điểm");
        bt_xemdiem.setName("bt_xemdiem"); // NOI18N
        bt_xemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemdiemActionPerformed(evt);
            }
        });

        bt_doimatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_doimatkhau.setText("Đổi Mật Khẩu");
        bt_doimatkhau.setName("bt_doimk"); // NOI18N
        bt_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_doimatkhauActionPerformed(evt);
            }
        });

        bt_dangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_dangxuat.setText("Đăng Xuất");
        bt_dangxuat.setName("bt_doimk"); // NOI18N
        bt_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_doimatkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(bt_xemdiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bt_xemdiem)
                .addGap(21, 21, 21)
                .addComponent(bt_doimatkhau)
                .addGap(21, 21, 21)
                .addComponent(bt_dangxuat)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_doimatkhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau doimk = new DoiMatKhau();
        doimk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_doimatkhauActionPerformed

    private void bt_xemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemdiemActionPerformed
        // TODO add your handling code here:
        SinhVienXemDiem svxd = new SinhVienXemDiem();
        svxd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_xemdiemActionPerformed

    private void bt_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dangxuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_dangxuatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dangxuat;
    private javax.swing.JButton bt_doimatkhau;
    private javax.swing.JButton bt_xemdiem;
    // End of variables declaration//GEN-END:variables
}
