package QLSV;
import DAO.DiemLopMonDAO;
import DAO.TaoPhucKhaoDiemDAO;
import POJOS.Taophuckhaodiem;
import static QLSV.DangNhap.account;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class SinhVienXemDiem extends javax.swing.JFrame {
 
    static int idpk;
    static String malop="";
    static String mamon="";
    static String mssv="";
    static String hoten="";
    static float dgk;
    static float dck;
    static float dk;
    static float dt;
    private String[] columnNames = {
        "STT", "Mã lớp", "Mã môn", "Tên môn", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng", ""
    };
    /**
     * Creates new form SinhVien
     */
    public SinhVienXemDiem() {
        initComponents();
        xemdsdiem(account.getUser());
    }

    private void xemdsdiem(String mssv)
    {
        int stt=1;
        List<Object[]> dsd = DiemLopMonDAO.getlistdiemsv(mssv);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        if(dsd.size()>0)
        {
            for (Object[] d : dsd){
                String[] rows = new String[9];
                rows[0] = String.valueOf(stt);
                rows[1] = d[0].toString();
                rows[2] = d[1].toString();
                rows[3] = d[2].toString();
                rows[4] = d[3].toString();
                rows[5] = d[4].toString();
                rows[6] = d[5].toString();
                rows[7] = d[6].toString();
                if(Float.parseFloat(d[6].toString())>=5)
                {
                    rows[8] = "Đậu";
                }
                else
                {
                    rows[8] = "Rớt";
                }
                tableModel.addRow(rows);
                stt++;
            }
            jTable1.setModel(tableModel);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_quayve = new javax.swing.JButton();
        bt_xinphuckhao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("ĐIỂM SINH VIÊN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        bt_quayve.setText("Quay Về");
        bt_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quayveActionPerformed(evt);
            }
        });

        bt_xinphuckhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_xinphuckhao.setText("Xin Phúc Khảo Điểm");
        bt_xinphuckhao.setName("bt_xinpkdiem"); // NOI18N
        bt_xinphuckhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xinphuckhaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_quayve)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_xinphuckhao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(bt_quayve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_xinphuckhao)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quayveActionPerformed
        // TODO add your handling code here:
        SinhVien sv = new SinhVien();
        sv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_quayveActionPerformed

    private void bt_xinphuckhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xinphuckhaoActionPerformed
        // TODO add your handling code here:
        if(!malop.equals(""))
        {
            Taophuckhaodiem id=TaoPhucKhaoDiemDAO.getpk();
            idpk=id.getId();

            XinPhucKhao1 a = new XinPhucKhao1();
            a.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn môn cần phúc khảo.", "Notification", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_xinphuckhaoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        malop=model.getValueAt(i,1).toString();
        mamon=model.getValueAt(i,2).toString();
        mssv=account.getUser();
        //hoten=model.getValueAt(i,2).toString();
        dgk=Float.parseFloat((String) model.getValueAt(i,4));
        dck=Float.parseFloat((String) model.getValueAt(i,5));
        dk=Float.parseFloat((String) model.getValueAt(i,6));
        dt=Float.parseFloat((String) model.getValueAt(i,7));
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_quayve;
    private javax.swing.JButton bt_xinphuckhao;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
