/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSV;


import DAO.LopDAO;
import DAO.SinhVienDAO;
import DAO.MonDAO;
import DAO.DiemLopMonDAO;
import POJOS.Lop;
import POJOS.SinhVien;
import POJOS.Mon;
import POJOS.Diemlopmon;
import POJOS.DiemlopmonId;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static QLSV.QuanLyTKB.malop;
import static QLSV.QuanLyTKB.mamon;

/**
 *
 * @author CPU12407-local
 */
public class ThemSinhVienMon extends javax.swing.JDialog {

    /**
     * Creates new form add
     */
    public ThemSinhVienMon() {
        initComponents();
        initLayoutlop();
        initLayoutmon();
        jcb_lop.setEnabled(false);
        jcb_mon.setEnabled(false);
    }

    private void initLayoutlop() {
        DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
        comboboxModel.addElement(malop);
        jcb_lop.setModel(comboboxModel);
    }
    
    private void initLayoutmon() {
        DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
        comboboxModel.addElement(mamon);
        jcb_mon.setModel(comboboxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSex = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txt_mssv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_themsinhvien = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcb_lop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        bt_quayve = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcb_mon = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sinh viên");

        txt_mssv.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("MSSV:");

        bt_themsinhvien.setText("Thêm");
        bt_themsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themsinhvienActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Mã lớp:");

        jcb_lop.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_lopActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("THÊM SINH VIÊN VÀO MÔN HỌC");

        bt_quayve.setText("Quay Về");
        bt_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quayveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel8.setText("Mã môn:");

        jcb_mon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcb_mon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_monActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_lop, 0, 181, Short.MAX_VALUE)
                            .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bt_themsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(bt_quayve, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcb_lop, txt_mssv});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcb_mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_themsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_quayve, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcb_lop, txt_mssv});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themsinhvienActionPerformed
        String mssv = txt_mssv.getText();
        String malop = String.valueOf(jcb_lop.getItemAt(jcb_lop.getSelectedIndex()));
        String mamon = String.valueOf(jcb_mon.getItemAt(jcb_mon.getSelectedIndex()));
        if (!malop.isEmpty()) {
            
            DiemlopmonId dlmid = new DiemlopmonId(malop, mamon, mssv);
            Diemlopmon dlm = new Diemlopmon(dlmid);
            DiemLopMonDAO.create(dlm);
            if(DiemLopMonDAO.create(dlm)==true)
            {
                JOptionPane.showMessageDialog(null, "Thêm học sinh thành công.");
                txt_mssv.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Thêm học sinh không thành công.");
            }          
        }
    }//GEN-LAST:event_bt_themsinhvienActionPerformed

    private boolean kiemtra(String mssv) {
        boolean kiemtra = false;
        StringBuilder msgErr = new StringBuilder();

        if (mssv.equals("")) {
            kiemtra = true;
            msgErr.append("Vui lòng nhập mssv.\n");
        }
        
        if(SinhVienDAO.getSinhVien(mssv)==null)
        {
            kiemtra = true;
            msgErr.append("Sinh viên chưa có trong lớp.\n");
        }
        
        if(kiemtra==true)
        {
            JOptionPane.showMessageDialog(this, msgErr);
        }
        return kiemtra;
    }
    
    private void bt_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quayveActionPerformed
        // TODO add your handling code here:
        QuanLyTKB qltkb = new QuanLyTKB();
        qltkb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_quayveActionPerformed

    private void jcb_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_lopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_lopActionPerformed

    private void jcb_monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_monActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSinhVienMon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_quayve;
    private javax.swing.JButton bt_themsinhvien;
    private javax.swing.ButtonGroup btgSex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox jcb_lop;
    private javax.swing.JComboBox jcb_mon;
    private javax.swing.JTextField txt_mssv;
    // End of variables declaration//GEN-END:variables
}
