/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSV;


import DAO.LopDAO;
import DAO.SinhVienDAO;
import POJOS.Lop;
import POJOS.SinhVien;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author CPU12407-local
 */
public class ThemSinhVien extends javax.swing.JDialog {

    private String className = "", idCourse = "";

    /**
     * Creates new form add
     */
    public ThemSinhVien() {
        initComponents();
        init();
        initLayout();
    }

    private void initLayout() {
        List<Lop> DSLop = LopDAO.getlistlop();
        if(DSLop.size()>0)
        {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            //System.out.println("có");
            for (Lop l : DSLop) {
                Lop _l = LopDAO.getlop(l.getMalop());
                comboboxModel.addElement(l.getMalop());
            }
            jcb_lop.setModel(comboboxModel);
        } else 
        {
            jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }
    
    /**
     *
     * @param _className
     */
    public ThemSinhVien(String _className) {
        this.className = _className;
        initComponents();
        init();
        String title = "Thêm Mới Học Sinh " + _className;
        //this.jLabel5.setText(title);
    }

    /**
     *
     * @param _className
     * @param _idCourse
     */
    public ThemSinhVien(String _className, String _idCourse) {
        this.className = _className;
        this.idCourse = _idCourse;
        initComponents();
        init();
        String title = "Thêm Mới Học Sinh " + _className + "-" + _idCourse;
        //this.jLabel5.setText(title);
    }

    private void init() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        if (this.idCourse.equals("")) {
            model.addElement(this.className);
        } else {
            model.addElement(this.className + '-' + this.idCourse);
        }
        jcb_lop.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSex = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txt_mssv = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        jtfCMND = new javax.swing.JTextField();
        jrbSex1 = new javax.swing.JRadioButton();
        jrbgioitinh = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_themsinhvien = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcb_lop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sinh viên");

        txt_mssv.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        txt_hoten.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        jtfCMND.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        btgSex.add(jrbSex1);
        jrbSex1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jrbSex1.setText("Nam");
        jrbSex1.setToolTipText("");

        btgSex.add(jrbgioitinh);
        jrbgioitinh.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jrbgioitinh.setText("Nữ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("MSSV:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Họ và tên:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Giới tính:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("CMND:");

        bt_themsinhvien.setText("Thêm");
        bt_themsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themsinhvienActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Mã lớp:");

        jcb_lop.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcb_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("THÊM SINH VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(bt_themsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_lop, javax.swing.GroupLayout.Alignment.TRAILING, 0, 181, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrbSex1)
                                .addGap(51, 51, 51)
                                .addComponent(jrbgioitinh)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcb_lop, jtfCMND, txt_hoten, txt_mssv});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbSex1)
                    .addComponent(jrbgioitinh)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(bt_themsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcb_lop, jtfCMND, txt_hoten, txt_mssv});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel6});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themsinhvienActionPerformed
//        String mssv = txt_mssv.getText();
//        String name = txt_hoten.getText();
//        String cmnd = jtfCMND.getText();
//        int sex = -1;
//
//        if (jrbSex1.isSelected()) {
//            sex = 0;
//        }
//
//        if (jrbgioitinh.isSelected()) {
//            sex = 1;
//        }
//
//        boolean validate = this.validateForm();
//        if (!validate) {
//            String nameClass = String.valueOf(jcb_lop.getItemAt(jcb_lop.getSelectedIndex()));
//            ClassRoom cr = ClassRoomDAO.getClassRoom(nameClass);
//            Student sd = new Student(mssv, name, sex, cmnd, cr);
//
//            boolean checkCreate = false;
//            if (this.idCourse.equals("")) {
//                checkCreate = StudentDAO.createStudent(sd);
//
//            } else {
//                ClassRoomCourse crc = new ClassRoomCourse(className, idCourse, mssv);
//                checkCreate = ClassRoomCourseDAO.addStudentInCourse(crc);
//            }
//
//            if (checkCreate) {
//                JOptionPane.showMessageDialog(null, "Thêm học sinh thành công.");
//                txt_mssv.setText("");
//                txt_hoten.setText("");
//                jtfCMND.setText("");
//            } else{
//                JOptionPane.showMessageDialog(null, "Thêm học sinh không thành công.");
//            } 
//
//        }
    }//GEN-LAST:event_bt_themsinhvienActionPerformed

  private boolean validateForm() {
        boolean validate = false;
        String mssv = txt_mssv.getText();
        String name = txt_hoten.getText();
        String cmnd = jtfCMND.getText();
        StringBuilder msgErr = new StringBuilder();

        if (this.idCourse.equals("")) {
            SinhVien sinhvien = SinhVienDAO.getSinhVien(mssv);
            if (sinhvien != null) {
                msgErr.append("MSSV đã tồn tại.");
                msgErr.append("\n");
            }
        } 
//        else {
//            ClassRoomCourse classRoomCourse = school.getClassRoomCourse(this.className, this.idCourse);
//            for (SinhVien sinhVien : classRoomCourse.getListSinhVien()) {
//                if (sinhVien.checkMSSV(mssv)) {
//                    msgErr.append("MSSV đã tồn tại.");
//                    msgErr.append("\n");
//                }
//            }
//        }

        if (mssv.equals("")) {
            validate = true;
            msgErr.append("MSSV không thể trống");
            msgErr.append("\n");
        }

        if (name.equals("")) {
            validate = true;
            msgErr.append("Tên không thể trống");
            msgErr.append("\n");
        }

        if (cmnd.equals("")) {
            validate = true;
            msgErr.append("CMND không thể trống");
            msgErr.append("\n");

        }

        if (jrbSex1.isSelected() == false && jrbgioitinh.isSelected() == false) {
            validate = true;
            msgErr.append("Vui lòng chọn giới tính");
            msgErr.append("\n");
        }

        if (validate == true) {
            JOptionPane.showMessageDialog(null, msgErr, "Error", JOptionPane.ERROR_MESSAGE);
        }

        return validate;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_themsinhvien;
    private javax.swing.ButtonGroup btgSex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcb_lop;
    private javax.swing.JRadioButton jrbSex1;
    private javax.swing.JRadioButton jrbgioitinh;
    private javax.swing.JTextField jtfCMND;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_mssv;
    // End of variables declaration//GEN-END:variables
}
