package POJOS;
// Generated Aug 24, 2019 9:43:46 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Taophuckhaodiem generated by hbm2java
 */
public class Taophuckhaodiem  implements java.io.Serializable {


     private int id;
     private Date ngaybd;
     private Date ngaykt;

    public Taophuckhaodiem() {
    }

	
    public Taophuckhaodiem(int id) {
        this.id = id;
    }
    public Taophuckhaodiem(Date ngaybd, Date ngaykt) {
       this.ngaybd = ngaybd;
       this.ngaykt = ngaykt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getNgaybd() {
        return this.ngaybd;
    }
    
    public void setNgaybd(Date ngaybd) {
        this.ngaybd = ngaybd;
    }
    public Date getNgaykt() {
        return this.ngaykt;
    }
    
    public void setNgaykt(Date ngaykt) {
        this.ngaykt = ngaykt;
    }
}


