package POJOS;
// Generated Aug 24, 2019 4:17:53 PM by Hibernate Tools 4.3.1



/**
 * XinphuckhaodiemId generated by hbm2java
 */
public class XinphuckhaodiemId  implements java.io.Serializable {


     private int id;
     private String mssv;
     private String mamon;
     private String malop;

    public XinphuckhaodiemId() {
    }

    public XinphuckhaodiemId(int id, String mssv, String mamon, String malop) {
       this.id = id;
       this.mssv = mssv;
       this.mamon = mamon;
       this.malop = malop;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof XinphuckhaodiemId) ) return false;
		 XinphuckhaodiemId castOther = ( XinphuckhaodiemId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) )
 && ( (this.getMamon()==castOther.getMamon()) || ( this.getMamon()!=null && castOther.getMamon()!=null && this.getMamon().equals(castOther.getMamon()) ) )
 && ( (this.getMalop()==castOther.getMalop()) || ( this.getMalop()!=null && castOther.getMalop()!=null && this.getMalop().equals(castOther.getMalop()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         result = 37 * result + ( getMamon() == null ? 0 : this.getMamon().hashCode() );
         result = 37 * result + ( getMalop() == null ? 0 : this.getMalop().hashCode() );
         return result;
   }   


}


