package POJOS;
// Generated Aug 24, 2019 4:17:53 PM by Hibernate Tools 4.3.1



/**
 * Xinphuckhaodiem generated by hbm2java
 */
public class Xinphuckhaodiem  implements java.io.Serializable {


     public XinphuckhaodiemId id;
     private String hoten;
     private Float diemgk;
     private Float diemck;
     private Float diemkhac;
     private Float diemtong;
     private String lido;
     private Integer tinhtrang;

    public Xinphuckhaodiem() {
    }

	
    public Xinphuckhaodiem(XinphuckhaodiemId id, String hoten, String lido) {
        this.id = id;
        this.hoten = hoten;
        this.lido = lido;
    }
    public Xinphuckhaodiem(XinphuckhaodiemId id, String hoten, Float diemgk, Float diemck, Float diemkhac, Float diemtong, String lido, Integer tinhtrang) {
       this.id = id;
       this.hoten = hoten;
       this.diemgk = diemgk;
       this.diemck = diemck;
       this.diemkhac = diemkhac;
       this.diemtong = diemtong;
       this.lido = lido;
       this.tinhtrang = tinhtrang;
    }
   
    public XinphuckhaodiemId getId() {
        return this.id;
    }
    
    public void setId(XinphuckhaodiemId id) {
        this.id = id;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public Float getDiemgk() {
        return this.diemgk;
    }
    
    public void setDiemgk(Float diemgk) {
        this.diemgk = diemgk;
    }
    public Float getDiemck() {
        return this.diemck;
    }
    
    public void setDiemck(Float diemck) {
        this.diemck = diemck;
    }
    public Float getDiemkhac() {
        return this.diemkhac;
    }
    
    public void setDiemkhac(Float diemkhac) {
        this.diemkhac = diemkhac;
    }
    public Float getDiemtong() {
        return this.diemtong;
    }
    
    public void setDiemtong(Float diemtong) {
        this.diemtong = diemtong;
    }
    public String getLido() {
        return this.lido;
    }
    
    public void setLido(String lido) {
        this.lido = lido;
    }
    public Integer getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(Integer tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
}


